[debug] [2017-09-25T11:53:33.456Z] ----------------------------------------------------------------------
[debug] [2017-09-25T11:53:33.461Z] Command:       /usr/local/bin/node /usr/local/bin/firebase serve --only functions,hosting
[debug] [2017-09-25T11:53:33.462Z] CLI Version:   3.11.0
[debug] [2017-09-25T11:53:33.462Z] Platform:      darwin
[debug] [2017-09-25T11:53:33.462Z] Node Version:  v6.11.2
[debug] [2017-09-25T11:53:33.465Z] Time:          Mon Sep 25 2017 04:53:33 GMT-0700 (PDT)
[debug] [2017-09-25T11:53:33.465Z] ----------------------------------------------------------------------
[debug] 
[debug] [2017-09-25T11:53:33.492Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2017-09-25T11:53:33.492Z] > authorizing via signed-in user
[debug] [2017-09-25T11:53:33.495Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/calculator-sid  
 Mon Sep 25 2017 04:53:33 GMT-0700 (PDT)
[debug] [2017-09-25T11:53:34.086Z] <<< HTTP RESPONSE 200
[debug] [2017-09-25T11:53:34.089Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/database/calculator-sid/tokens  
 Mon Sep 25 2017 04:53:34 GMT-0700 (PDT)
[debug] [2017-09-25T11:53:34.625Z] <<< HTTP RESPONSE 200
[info] 
[info] === Serving from '/Users/sidgore/Documents/Calculator'...
[info] 
[debug] [2017-09-25T11:53:35.695Z] Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/logs'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:923:18)
    at Object.assertLogsPath (/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/emulator/logs.js:65:10)
    at new Controller (/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/cli/controller.js:85:32)
    at FunctionsEmulator.start (/usr/local/lib/node_modules/firebase-tools/lib/functionsEmulator.js:110:21)
    at Object.start (/usr/local/lib/node_modules/firebase-tools/lib/serve/functions.js:9:29)
    at /usr/local/lib/node_modules/firebase-tools/lib/serve/index.js:16:19
    at arrayMap (/usr/local/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:660:23)
    at Function.map (/usr/local/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:9571:14)
    at _serve (/usr/local/lib/node_modules/firebase-tools/lib/serve/index.js:14:21)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2017-09-25T11:54:08.365Z] ----------------------------------------------------------------------
[debug] [2017-09-25T11:54:08.368Z] Command:       /usr/local/bin/node /usr/local/bin/firebase serve --only functions,hosting
[debug] [2017-09-25T11:54:08.369Z] CLI Version:   3.11.0
[debug] [2017-09-25T11:54:08.369Z] Platform:      darwin
[debug] [2017-09-25T11:54:08.369Z] Node Version:  v6.11.2
[debug] [2017-09-25T11:54:08.370Z] Time:          Mon Sep 25 2017 04:54:08 GMT-0700 (PDT)
[debug] [2017-09-25T11:54:08.370Z] ----------------------------------------------------------------------
[debug] 
[debug] [2017-09-25T11:54:08.391Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2017-09-25T11:54:08.391Z] > authorizing via signed-in user
[debug] [2017-09-25T11:54:08.395Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/calculator-sid  
 Mon Sep 25 2017 04:54:08 GMT-0700 (PDT)
[debug] [2017-09-25T11:54:08.772Z] <<< HTTP RESPONSE 200
[debug] [2017-09-25T11:54:08.773Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/database/calculator-sid/tokens  
 Mon Sep 25 2017 04:54:08 GMT-0700 (PDT)
[debug] [2017-09-25T11:54:09.138Z] <<< HTTP RESPONSE 200
[info] 
[info] === Serving from '/Users/sidgore/Documents/Calculator'...
[info] 
[debug] [2017-09-25T11:54:10.079Z] Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/logs'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:923:18)
    at Object.assertLogsPath (/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/emulator/logs.js:65:10)
    at new Controller (/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/cli/controller.js:85:32)
    at FunctionsEmulator.start (/usr/local/lib/node_modules/firebase-tools/lib/functionsEmulator.js:110:21)
    at Object.start (/usr/local/lib/node_modules/firebase-tools/lib/serve/functions.js:9:29)
    at /usr/local/lib/node_modules/firebase-tools/lib/serve/index.js:16:19
    at arrayMap (/usr/local/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:660:23)
    at Function.map (/usr/local/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:9571:14)
    at _serve (/usr/local/lib/node_modules/firebase-tools/lib/serve/index.js:14:21)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2017-09-25T21:50:30.894Z] ----------------------------------------------------------------------
[debug] [2017-09-25T21:50:30.899Z] Command:       /usr/local/bin/node /usr/local/bin/firebase serve --only functions,hosting
[debug] [2017-09-25T21:50:30.900Z] CLI Version:   3.11.0
[debug] [2017-09-25T21:50:30.900Z] Platform:      darwin
[debug] [2017-09-25T21:50:30.900Z] Node Version:  v6.11.2
[debug] [2017-09-25T21:50:30.901Z] Time:          Mon Sep 25 2017 14:50:30 GMT-0700 (PDT)
[debug] [2017-09-25T21:50:30.901Z] ----------------------------------------------------------------------
[debug] 
[debug] [2017-09-25T21:50:30.928Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2017-09-25T21:50:30.928Z] > authorizing via signed-in user
[debug] [2017-09-25T21:50:30.931Z] > refreshing access token with scopes: ["email","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","openid"]
[debug] [2017-09-25T21:50:30.932Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token { refresh_token: '1/b1E8MFa_M8LDAUyVR8p8HwY0Z3LqkZjBpWVDnqKDaog',
  client_id: '563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com',
  client_secret: 'j9iVZfS8kkCEFUPaAeJV0sAi',
  grant_type: 'refresh_token',
  scope: 'email https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/cloudplatformprojects.readonly https://www.googleapis.com/auth/firebase openid' } 
 Mon Sep 25 2017 14:50:30 GMT-0700 (PDT)
[debug] [2017-09-25T21:50:31.152Z] <<< HTTP RESPONSE 200
[debug] [2017-09-25T21:50:31.169Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/calculator-sid  
 Mon Sep 25 2017 14:50:31 GMT-0700 (PDT)
[debug] [2017-09-25T21:50:32.715Z] <<< HTTP RESPONSE 200
[debug] [2017-09-25T21:50:32.716Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/database/calculator-sid/tokens  
 Mon Sep 25 2017 14:50:32 GMT-0700 (PDT)
[debug] [2017-09-25T21:50:33.141Z] <<< HTTP RESPONSE 500
[debug] [2017-09-25T21:50:33.141Z] <<< HTTP RESPONSE BODY
[error] 
[error] Error: HTTP Error: 500, An unknown error occurred. Please contact support.
[debug] [2017-09-25T21:50:33.302Z] Error Context: {
  "body": {
    "error": {
      "code": "UNKNOWN_ERROR",
      "message": "An unknown error occurred. Please contact support."
    }
  },
  "response": {
    "statusCode": 500,
    "body": {
      "error": {
        "code": "UNKNOWN_ERROR",
        "message": "An unknown error occurred. Please contact support."
      }
    },
    "headers": {
      "server": "nginx",
      "date": "Mon, 25 Sep 2017 21:50:32 GMT",
      "content-type": "application/json; charset=utf-8",
      "content-length": "97",
      "connection": "close",
      "x-content-type-options": "nosniff"
    },
    "request": {
      "uri": {
        "protocol": "https:",
        "slashes": true,
        "auth": null,
        "host": "admin.firebase.com",
        "port": 443,
        "hostname": "admin.firebase.com",
        "hash": null,
        "search": null,
        "query": null,
        "pathname": "/v1/database/calculator-sid/tokens",
        "path": "/v1/database/calculator-sid/tokens",
        "href": "https://admin.firebase.com/v1/database/calculator-sid/tokens"
      },
      "method": "GET"
    }
  }
}
[debug] [2017-09-25T21:51:25.452Z] ----------------------------------------------------------------------
[debug] [2017-09-25T21:51:25.455Z] Command:       /usr/local/bin/node /usr/local/bin/firebase serve --only functions,hosting
[debug] [2017-09-25T21:51:25.456Z] CLI Version:   3.11.0
[debug] [2017-09-25T21:51:25.456Z] Platform:      darwin
[debug] [2017-09-25T21:51:25.456Z] Node Version:  v6.11.2
[debug] [2017-09-25T21:51:25.456Z] Time:          Mon Sep 25 2017 14:51:25 GMT-0700 (PDT)
[debug] [2017-09-25T21:51:25.456Z] ----------------------------------------------------------------------
[debug] 
[debug] [2017-09-25T21:51:25.471Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2017-09-25T21:51:25.471Z] > authorizing via signed-in user
[debug] [2017-09-25T21:51:25.475Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/calculator-sid  
 Mon Sep 25 2017 14:51:25 GMT-0700 (PDT)
[debug] [2017-09-25T21:51:25.921Z] <<< HTTP RESPONSE 200
[debug] [2017-09-25T21:51:25.923Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/database/calculator-sid/tokens  
 Mon Sep 25 2017 14:51:25 GMT-0700 (PDT)
[debug] [2017-09-25T21:51:26.365Z] <<< HTTP RESPONSE 500
[debug] [2017-09-25T21:51:26.365Z] <<< HTTP RESPONSE BODY
[error] 
[error] Error: HTTP Error: 500, An unknown error occurred. Please contact support.
[debug] [2017-09-25T21:51:26.504Z] Error Context: {
  "body": {
    "error": {
      "code": "UNKNOWN_ERROR",
      "message": "An unknown error occurred. Please contact support."
    }
  },
  "response": {
    "statusCode": 500,
    "body": {
      "error": {
        "code": "UNKNOWN_ERROR",
        "message": "An unknown error occurred. Please contact support."
      }
    },
    "headers": {
      "server": "nginx",
      "date": "Mon, 25 Sep 2017 21:51:25 GMT",
      "content-type": "application/json; charset=utf-8",
      "content-length": "97",
      "connection": "close",
      "x-content-type-options": "nosniff"
    },
    "request": {
      "uri": {
        "protocol": "https:",
        "slashes": true,
        "auth": null,
        "host": "admin.firebase.com",
        "port": 443,
        "hostname": "admin.firebase.com",
        "hash": null,
        "search": null,
        "query": null,
        "pathname": "/v1/database/calculator-sid/tokens",
        "path": "/v1/database/calculator-sid/tokens",
        "href": "https://admin.firebase.com/v1/database/calculator-sid/tokens"
      },
      "method": "GET"
    }
  }
}
[debug] [2017-09-25T21:57:39.861Z] ----------------------------------------------------------------------
[debug] [2017-09-25T21:57:39.865Z] Command:       /usr/local/bin/node /usr/local/bin/firebase serve --only functions,hosting
[debug] [2017-09-25T21:57:39.865Z] CLI Version:   3.11.0
[debug] [2017-09-25T21:57:39.866Z] Platform:      darwin
[debug] [2017-09-25T21:57:39.866Z] Node Version:  v6.11.2
[debug] [2017-09-25T21:57:39.868Z] Time:          Mon Sep 25 2017 14:57:39 GMT-0700 (PDT)
[debug] [2017-09-25T21:57:39.869Z] ----------------------------------------------------------------------
[debug] 
[debug] [2017-09-25T21:57:39.891Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2017-09-25T21:57:39.892Z] > authorizing via signed-in user
[debug] [2017-09-25T21:57:39.895Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/calculator-sid  
 Mon Sep 25 2017 14:57:39 GMT-0700 (PDT)
[debug] [2017-09-25T21:57:40.632Z] <<< HTTP RESPONSE 200
[debug] [2017-09-25T21:57:40.633Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/database/calculator-sid/tokens  
 Mon Sep 25 2017 14:57:40 GMT-0700 (PDT)
[debug] [2017-09-25T21:57:41.020Z] <<< HTTP RESPONSE 500
[debug] [2017-09-25T21:57:41.020Z] <<< HTTP RESPONSE BODY
[error] 
[error] Error: HTTP Error: 500, An unknown error occurred. Please contact support.
[debug] [2017-09-25T21:57:41.175Z] Error Context: {
  "body": {
    "error": {
      "code": "UNKNOWN_ERROR",
      "message": "An unknown error occurred. Please contact support."
    }
  },
  "response": {
    "statusCode": 500,
    "body": {
      "error": {
        "code": "UNKNOWN_ERROR",
        "message": "An unknown error occurred. Please contact support."
      }
    },
    "headers": {
      "server": "nginx",
      "date": "Mon, 25 Sep 2017 21:57:40 GMT",
      "content-type": "application/json; charset=utf-8",
      "content-length": "97",
      "connection": "close",
      "x-content-type-options": "nosniff"
    },
    "request": {
      "uri": {
        "protocol": "https:",
        "slashes": true,
        "auth": null,
        "host": "admin.firebase.com",
        "port": 443,
        "hostname": "admin.firebase.com",
        "hash": null,
        "search": null,
        "query": null,
        "pathname": "/v1/database/calculator-sid/tokens",
        "path": "/v1/database/calculator-sid/tokens",
        "href": "https://admin.firebase.com/v1/database/calculator-sid/tokens"
      },
      "method": "GET"
    }
  }
}
